- id: '1671823778675'
  alias: Smart PV Plug
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /1
    seconds: '0'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.smart_pv_plug_threshold
      attribute: position
      for:
        hours: 0
        minutes: 3
        seconds: 0
      state: above
    then:
    - type: turn_on
      device_id: 436f21aba3b17524c69060ed082579e3
      entity_id: switch.shelly_switch_channel_2
      domain: switch
    else:
    - if:
      - condition: state
        entity_id: binary_sensor.smart_pv_plug_threshold
        attribute: position
        state: below
        for:
          hours: 0
          minutes: 3
          seconds: 0
      then:
      - type: turn_off
        device_id: 436f21aba3b17524c69060ed082579e3
        entity_id: switch.shelly_switch_channel_2
        domain: switch
  mode: single
- id: '1671826077271'
  alias: WP Boiler force ON
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
    seconds: '0'
    hours: '*'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.wp_boiler_force_threshold
      attribute: position
      state: below
      for:
        hours: 0
        minutes: 5
        seconds: 0
    then:
    - type: turn_on
      device_id: 118b8c5734ac3b597bb20bdc016ae97c
      entity_id: switch.powermeter
      domain: switch
    else:
    - if:
      - condition: state
        entity_id: binary_sensor.wp_boiler_force_threshold
        attribute: position
        state: above
        for:
          hours: 0
          minutes: 5
          seconds: 0
      then:
      - type: turn_off
        device_id: 118b8c5734ac3b597bb20bdc016ae97c
        entity_id: switch.powermeter
        domain: switch
  mode: single
