- id: '1671220882092'
  alias: Smart PV plug controller
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.smart_pv_plug_threshold
    for:
      hours: 0
      minutes: 0
      seconds: 0
    attribute: sensor_value
  condition: []
  action:
  - service: script.smart_pv_surplus_powerplug
    data: {}
  mode: single
- id: '1671566074377'
  alias: WP Boiler Force Control
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.wp_boiler_force_threshold
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: script.wp_boiler_control
    data: {}
  mode: single
