sensor.powermeter_energy_total:
  last_reset: '1970-01-01T00:00:00+00:00'
  state_class: 'total_increasing'
  device_class: energy
  unit_of_measurement: kWh 
 
sensor.powermeter_energy_return_total:
  last_reset: '1970-01-01T00:00:00+00:00' 
  state_class: 'total_increasing'
  device_class: energy
  unit_of_measurement: kWh

sensor.solarplant_energy_total:
  last_reset: '1970-01-01T00:00:00+00:00'
  state_class: 'total_increasing'
  device_class: energy
  unit_of_measurement: kWh

sensor.solarplant_energy_return_total:
  last_reset: '1970-01-01T00:00:00+00:00'
  state_class: 'total_increasing'
  device_class: energy
  unit_of_measurement: kWh
