version: '3'
services:
#    db:
#        image: mariadb:10.9
#        restart: always
#        environment:
#            MARIADB_USER: mariadb_user
#            MARIADB_ROOT_PASSWORD: mariadb
#            MARIADB_DATABASE: mariadb
#        ports:
#            - 0.0.0.0:3808:3808

    mosquitto:
        image: eclipse-mosquitto:2
        volumes:
            - ./mosquitto:/mosquitto
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        ports:
            - 0.0.0.0:1883:1883
            - 0.0.0.0:8001:9001  

    homeassistant:
        container_name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        volumes:
            - /home/tv/dockerContainers/homeAssistant/config:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        privileged: true
        network_mode: host
        ports:
            - 0.0.0.0:8123:8123
        expose:
            - 8123
